### PR TITLE
Fix default value for when the otel.smp.enabled property is not set

### PR DESCRIPTION
**Pull request by srprash**
*Description of changes:*
The functionality should be explicitly opt-in.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by bryan-aguilar — APPROVED** [review]

**Review by mxiamxia — APPROVED** [review]

**Comment by itstheceo** [comment]
Could this change of default value result in a substantial increase of APM data?

**Comment by srprash** [comment]
>Could this change of default value result in a substantial increase of APM data?

Quite the opposite. Setting the `otel.smp.enabled` to `true` will tell the ADOT agent to generate some extra APM data for  [ApplicationSignals](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Monitoring-Sections.html).

**Comment by itstheceo** [comment]
@srprash Thanks for the prompt reply. I have observed a massive increase in APM data for my service over the last 3-4 weeks, though setting `otel.smp.enabled` to `true` appears to be unrelated as you say. There hasn't been much change in this service, mostly bumping dependencies. I am still trying to track down the cause as it's only recently been brought to my attention. From my investigation, fields such as `http.server.duration` are no longer being bucketed into a histogram, which is resulting in a huge increase of documents. I will keep digging.

**Comment by itstheceo** [comment]
Ended up reverting the agent to 1.29.0, and the issue is no longer happening.

**Comment by srprash** [comment]
@itstheceo What was the version of the ADOT agent where you noticed the issue?

**Comment by itstheceo** [comment]
@srprash I suspect something changed in 1.31.x. The issue happened in two services I am responsible for, both had similar symptoms. They do use distributed tracing with each other, whether that's relevant or not. 

It felt like rather than the agent sending the delta, it repeatedly sent everything which was accumulating over time. As you can see following, the subtle gradient trending up. It did eventually level out, assuming when a buffer reached capacity.
Screenshot 2023-12-13 at 11 44 28 AM

And after reverting `aws-opentelemetry-agent` to 1.29.0, traffic returned to normal.
Screenshot 2023-12-13 at 11 44 42 AM

**Comment by bryan-aguilar** [comment]
Thank you @itstheceo,

Was this issue present with both `1.31.0` and `1.31.1`?

**Comment by itstheceo** [comment]
@bryan-aguilar not sure yet. I'll try to set aside some time for testing this week and get back to you.

**Comment by bryan-aguilar** [comment]
That would be helpful, ty. But also, #648

**Pull request merged**
